### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by mscheltienne** [fcbg-hnp-meeg/demo-realtime#9]
@hoechenberger This is the repository where we have the small demo with a topographic map updating live. We use this with DSI-24 dry electrode EEGs, which have very poor signal quality, but well, good enough for short demos ;)

The topomap code is here: https://github.com/fcbg-hnp-meeg/demo-realtime/blob/main/demo_realtime/visuals/topomap.py
The loop using the topomap is here: https://github.com/fcbg-hnp-meeg/demo-realtime/blob/main/demo_realtime/rt_topomap.py

If you want to give it a shot, you can mock a stream from the `dsi-24-raw.fif` file here: https://github.com/fcbg-hnp-meeg/demo-realtime/tree/main/data

```
from mne_lsl.player import PlayerLSL

from demo_realtime import rt_topomap

fname = "..."
with PlayerLSL(fname, chunk_size=10, name="test"):
    rt_topomap("test")
```

IIRC, one of the channels in this recording used to mock a stream is bad, and should be added to this list: https://github.com/fcbg-hnp-meeg/demo-realtime/blob/d68a54a7630d867f79555597bf24c057bd5e332b/demo_realtime/rt_topomap.py#L44

**Comment by hoechenberger** [comment]
Thanks @mscheltienne, really cool!!!
